permalink: /:categories/:title/
url: "http://www.prtxhn.de"
full_name: "PRTXHN - gediegen ist für Spandau"
first_name: "PRTXHN"
last_name: "Piratenpartei Friedrichshain-Kreuzberg"
blog_title: "PRTXHN"
author_img_name_path: "/images/users/user.jpg"
#disqus_shortname: "example"
copyright_year: "2016"
google_analytics_code: ""
aboutme: "PRTXHN ist unser Vietnam"
